### PR TITLE
Update `umlsSynsets.txt` MD5

### PR DESCRIPTION
**Pull request by michelole**
@khituras Could you confirm the new MD5?

### CODE REVIEW

**Comment by michelole** [comment]
Here we come again... Sorting doesn't change the file for me.

```
$ du umlsSynsets.txt
671872	umlsSynsets.txt
$ head -1 umlsSynsets.txt
C0000005 	 (131)I-MAA	(131)I-Macroaggregated Albumin
```

**Comment by khituras** [comment]
Your file is much larger than mine:

faessler@dawkins:~/Coding/git/trec-pm/resources$ du umlsSynsets.txt
330524	umlsSynsets.txt
faessler@dawkins:~/Coding/git/trec-pm/resources$ head umlsSynsets.txt
C0000005 	 (131)I-MAA	(131)I-Macroaggregated Albumin

Lets re-check our MRCONSO.RRF files. I got a new one from the full download I did. But it should be the same as before:

faessler@h5:/data/data_resources/UMLS/UMLS2019/2019AA/META$ wc -l MRCONSO.RRF
14608809 MRCONSO.RRF
faessler@h5:/data/data_resources/UMLS/UMLS2019/2019AA/META$ du MRCONSO.RRF
1816888	MRCONSO.RRF
faessler@h5:/data/data_resources/UMLS/UMLS2019/2019AA/META$ md5sum MRCONSO.RRF
fd34e41376441439c37d89105a73c6b5  MRCONSO.RRF

**Comment by michelole** [comment]
Just realized that `du` is not a proper tool to compare sizes because the cluster size on APFS and ext4 may be different.

What about number of bytes as reported by `wc`?
```
✗ wc -c umlsSynsets.txt
 338449057 umlsSynsets.txt
```

Source file seems to be OK:
```
➜  umls wc -l MRCONSO.RRF
 14608809 MRCONSO.RRF
➜  umls du MRCONSO.RRF
3635256	MRCONSO.RRF
➜  umls wc -c MRCONSO.RRF 
 1860486173 MRCONSO.RRF
➜  umls md5sum MRCONSO.RRF 
fd34e41376441439c37d89105a73c6b5  MRCONSO.RRF
```

**Comment by khituras** [comment]
I see XD

faessler@dawkins:~/Coding/git/trec-pm/resources$ wc -c umlsSynsets.txt
338449057 umlsSynsets.txt

So this seems fine.

**Pull request merged**
