### PR TITLE
Issue 18

### LINKED ISSUE #18: Add "inverse" methods to `AtomicGoldStandard`
Add methods to `AtomicGoldStandard` so that it can be created inline and dump data into a .qrels file.

Related to #8.

### PR DESCRIPTION
**Pull request by michelole**
This fixes #18.

### CODE REVIEW

**Comment by khituras** [comment]
So it's perfectly possible that I didn't yet understand everything, please bear with me :-)
I understand that the main purpose of the PR is to allow an `AtomicGoldstandard` not write a qrel file for a given document list. Why do we need this? When will we have the document objects first - with relevance judgments, query number etc. - and no qrel file that should then be written? Why not just create the qrel file in the first place?

**Comment by michelole** [comment]
Well, if you need to create the qrels file in the first place, then there's no better place to put the _writing_ logic than right under the _reading_ logic...

Anyway, this is required for #8, when we'll have a GS that's backed by a cloud spreadsheet. I do plan to still write the corresponding qrels file and I thought it would make sense to have "inverse" methods (from `DocumentList` to qrels file) also in `TrecQrelGoldStandard`.

It seems to fit well apart from the apparent need to have both a traditional and a sample qrels file. Maybe in the future `TrecQrelGoldStandard` should encapsulate a _single_ file only and then we could group both type of files using `AggregatedGoldStandard`.

**Comment by khituras** [comment]
I see the point of having the input and output logic packed together. I have, however, issues with a class that does very different things depending on the used constructor: In one case, it *reads* the qrels file, in the other it *writes* the qrels file which, for me, practically calls for issues of overriding an official qrels file by accident.
May I propose to instead externalize the read/write logic altoghether in some class `QrelIO` or similar? There, we could just add all possible input/output conversion methods we need and use them freely without causing confusion about what a GoldStandard does and what it does not.

Alternatively - and closer to the thinking of the PR - we could change the `AtomicGoldStandard` to just take some source of relevance judged documents, be it a `QRels file`, a `DocumentList` or the link to a `GoogleSheet` and initialize from that source. For evaluation purposes, the GS would then **always** print out a newly generated QRels file - in the case a QRels file was also the input, it would just be a copy - into some temporary evaluation directory. This newly written file would then be used to compute the evaluation metrics.
This would avoid the danger of overwriting a source file and provide a clean model and interface (of course I imagine some `QrelSource` class or interface abstracting away the file, DocumentList or GoogleSheet).

Would one of those ideas find your agreement?

**Comment by michelole** [comment]
I see your point and agree with you.

Actually, a constructor that writes to a file as a side effect doesn't sound good. Maybe this should be lazily done on the`getQrelFile` method?

And indeed, the current implementation seems somehow clumsy: one could modify the `qrelDocuments` attribute after initialization, but would get a file with the old documents in the `getQrelFile` method!

**Comment by khituras** [comment]
Interesting points, especially the second (modifications to the in-memory documents are not reflected by the  qrels file).

So I would currently prefer my second proposed solution. We would
* Replace the QRel file input with a general "QrelSource" object (or similarly named)
* Add a method `writeQrelFile(File)` which
  * Writes a QRel file reflecting the actual state of the `GoldStandard`'s documents
  * Set the internal `qrelFile` field which would be null up to this point.

Overwriting would then only happen when the path given to `writeQrelFile`  explicitly points to an existing file, the written QRel file would always reflect the current state of the - possibily modified - `DocumentList` and one still would have access the original Qrel source via the `QrelSource` object.

What's your opinion on that?

**Comment by michelole** [comment]
That's interesting. I don't see a reason to keep a `qrelFile` though, as it'd also be somehow redundant with `QrelSource`. `writeQrelFile(File)` could be a replacement to `getQrelFile` --- if you want to keep  the getter, we could still write to a temp file (with `writeQrelFile`) and return it back.

**Comment by khituras** [comment]
I had the same thought, that `writeQrelFile(File)` should just return the file. The getter would just realize some sense of caching. We can leave it out.

**Comment by michelole** [comment]
I implemented `writeQrelFile(File)`. If it's ok for you, I'd merge this now and introduce `QrelSource` as part of #8.

**Pull request merged**
